
package(default_visibility = ["//visibility:public"])

load(
    #"//:mediapipe_graph.bzl",
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

exports_files(["sign_lang_prediction_gpu.pbtxt"])
